<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>WishBuilder.CredentialService.Tests</AssemblyName>
    <RootNamespace>WishBuilder.CredentialService.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/WishBuilder.CredentialService/WishBuilder.CredentialService.csproj" />
  </ItemGroup>
</Project>
