<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>WishBuilder.CredentialService.Tests</AssemblyName>
    <RootNamespace>WishBuilder.CredentialService.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MSTest.TestFramework" />
    <ProjectReference Include="../../../src/WishBuilder.CredentialService/WishBuilder.CredentialService.csproj" />
  </ItemGroup>
</Project>
