"""Read-only, deterministic presentation surfaces."""

from .trace import (
    DEFAULT_TRACE_LIMITS,
    TRACE_SCHEMA_VERSION,
    TraceArtifacts,
    TraceExport,
    TraceExportError,
    TraceExportFault,
    TraceExportReason,
    TraceFaultCode,
    TraceLimits,
    TraceProjection,
    build_trace_projection,
    compile_trace,
    export_trace,
    render_trace_json,
    render_trace_markdown,
    trace_json_bytes,
    trace_json_sha256,
    trace_markdown_bytes,
    trace_markdown_sha256,
)

__all__ = [
    "DEFAULT_TRACE_LIMITS",
    "TRACE_SCHEMA_VERSION",
    "TraceArtifacts",
    "TraceExport",
    "TraceExportError",
    "TraceExportFault",
    "TraceExportReason",
    "TraceFaultCode",
    "TraceLimits",
    "TraceProjection",
    "build_trace_projection",
    "compile_trace",
    "export_trace",
    "render_trace_json",
    "render_trace_markdown",
    "trace_json_bytes",
    "trace_json_sha256",
    "trace_markdown_bytes",
    "trace_markdown_sha256",
]
